---
# file: main.yml

- hosts: localhost
  connection: local
  vars_prompt:
    - name: master_node
      prompt: "Please enter the FQDN of the master node"

    - name: standby_node
      prompt: "Please enter the FQDN of the standby node to be configured"

    - name: ansible_password
      prompt: "Please enter the administrator password for remote host"
      private: yes

    - name: certPassword
      prompt: "Please enter the password for pfx certificate file"
      private: yes

    - name: hsm_partition_pin
      prompt: "Please enter the HSM Partition password"
      private: yes

    - name: hsm_admin_password
      prompt: "Please enter the HSM admin password"
      private: yes

  tasks:
    - include_tasks: tasks/set_facts.yml
    - include_tasks: tasks/download_files.yml
    - include_tasks: tasks/cert-gen.yml        

- name: Create the seed files
  hosts: "{{ master_node }}"

  tasks:
    - include_tasks: tasks/standby_seed_gen.yml

- name: Ensure Prerequisites are met on Standby servers
  hosts: "{{ standby_node }}"
  strategy: free

  tasks:
    - include_tasks: tasks/install_docker.yml
    - include_tasks: tasks/prerequsite.yml

- name: Perform HSM Integration
  hosts: "{{ standby_node }}"

  tasks:
    - include_tasks: tasks/hsm_integration.yml
      when: hsm_integartion|bool == true

- name: Deploy standby servers with HSM integration
  hosts: "{{ standby_node }}"
  strategy: free

  tasks:
    - include_tasks: tasks/standby.yml

#enable sync replication on new primary and standby
- name: Enable Synchronous Replication
  hosts: "{{ master_node }}"
  tasks:
    - include_tasks: tasks/sync_replication.yml
      vars:
        deployment_type: 'standby'
