- name: Download docker-ce.repo
  ansible.builtin.get_url:
    url: http://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
    mode: '0644'

- name: Ensure Docker is installed
  ansible.builtin.dnf:
    name: docker-ce
    state: present

- name: Create /etc/docker directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory

- name: create daemon-json file
  ansible.builtin.template:
    dest: /etc/docker/daemon.json
    src: template/docker-daemon.json.j2

- name: Start Docker
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started
