---
- name: Log which client is being registered to HSM
  debug:
    msg: "Registering client: {{ client_name }} [host: {{ client_host }}, CN: {{ client_cert_cn }}] with HSM: {{ hsm_hostname }}"

- name: Get the hsm server cert from the hsm_server
  ansible.builtin.expect:
    command: >
      /bin/scp -o StrictHostKeyChecking=no admin@{{ hsm_hostname }}:server.pem 
      /usr/safenet/lunaclient/bin/{{ hsm_hostname }}.pem
    creates: "/usr/safenet/lunaclient/bin/{{ hsm_hostname }}.pem"
    responses:
      password: "{{ hsm_admin_password }}"
  no_log: true

- name: Register the HSM server cert with the client
  ansible.builtin.shell: >
    /usr/safenet/lunaclient/bin/vtl addServer -n {{ hsm_hostname }}
    -c /usr/safenet/lunaclient/bin/{{ hsm_hostname }}.pem
  register: add_server
  become: true
  failed_when:
    - add_server.rc != 0
    - '"This server is already registered" not in add_server.stdout'

- name: Check for existing clients
  ansible.builtin.expect:
    command: >
      /bin/ssh -o StrictHostKeyChecking=false -c aes256-ctr admin@{{ hsm_hostname }} 
      -C client list
    responses:
      password: "{{ hsm_admin_password }}"
  register: client_list
  no_log: true

- name: Fail if client is already registered, but we don't have that cert
  ansible.builtin.fail:
    msg: "Client: {{ client_name }} is already registered, but the client cert is missing!"
  when:
    - client_name in client_list.stdout
    - client_new_cert
    - not lunasa_client_rotate_cert

- name: Delete existing client when rotating certs
  ansible.builtin.expect:
    command: >
      /bin/ssh -o StrictHostKeyChecking=false -c aes256-ctr admin@{{ hsm_hostname }} 
      -C "client delete -f -c {{ client_name }}"
    responses:
      password: "{{ hsm_admin_password }}"
  when:
    - client_name in client_list.stdout
    - lunasa_client_rotate_cert
  no_log: true

- name: Register the client certificate on the hsm_server
  block:
    - name: Copy the NTL client cert to the HSM
      ansible.builtin.expect:
        command: >
          /bin/scp -o StrictHostKeyChecking=no -c aes256-ctr /usr/safenet/lunaclient/cert/client/{{ client_cert_cn }}.pem
          admin@{{ hsm_hostname }}:{{ client_host }}.pem
        responses:
          password: "{{ hsm_admin_password }}"

    - name: Register the client
      ansible.builtin.expect:
        command: >
          ssh -c aes256-ctr admin@{{ hsm_hostname }}
          -C "client register -c {{ client_name }} {{ client_reg_opt }} {{ client_host }}"
        responses:
          password: "{{ hsm_admin_password }}"
      register: client_register
      failed_when:
        - client_register.rc != 0
        - "'client with the same IP address has already been registered' not in client_register.stdout"
  become: true
  when: client_name not in client_list.stdout or lunasa_client_rotate_cert
  no_log: true

- name: Assign client to an HSM partition
  ansible.builtin.expect:
    command: >
      /bin/ssh -c aes256-ctr admin@{{ hsm_hostname }}
      -C "client assignPartition -c {{ client_name }} -p {{ hsm_partition }}"
    responses:
      password: "{{ hsm_admin_password }}"
  register: assign_partition
  failed_when:
    - assign_partition.rc != 0
    - "'client already has access' not in assign_partition.stdout"
  become: true
  no_log: true
